/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <pthread.h>
#include <unistd.h>
#include <android/log.h>
#include <sys/system_properties.h>
#include <stdlib.h>
#include <fcntl.h>
#include <time.h>



//#include <string>
#include <dlfcn.h>
#include <string.h>

#include <android/log.h>

//#if defined(__aarch64__)
//
//#include "And64InlineHook.hpp"
//
//#elif defined(__arm__)
//#endif
//
//#ifndef _Included_com_wrbug_xposeddemo_Native
//#define _Included_com_wrbug_xposeddemo_Native
//#ifdef __cplusplus
//extern "C" {
//
//#endif
///*
// * Class:     com_wrbug_xposeddemo_Native
// * Method:    test
// * Signature: ()Ljava/lang/String;
// */
//JNIEXPORT void JNICALL Java_com_wrbug_dumpdex_Native_dump
//        (JNIEnv *, jclass, jstring);
//
//
//#ifdef __cplusplus
//}
#ifndef JNI_LOG_H
#define JNI_LOG_H
void LOGI(const char *tag, const char *fmt, ...);

void LOGW(const char *tag, const char *fmt, ...);

void LOGE(const char *tag, const char *fmt, ...);

#endif JNI_LOG_H
//#endif
//#endif
